server:
  port: 9090
  servlet:
    context-path: /hi/

spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    # mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  devtools:
    # 开启热部署
    restart:
      enabled: true
      # 监听目录
      additional-paths: src/main/java
  profiles:
    active: dev

my:
  name: jiaohongtao
